/* ============================================================
   COLLIDOSCOPE — Particle Database
   All values from the Particle Data Group (PDG 2024).
   threshold = approximate √s (GeV) needed to produce the
   particle in a collision (≈ pair-production / resonance
   energy, simplified for gameplay).
   ============================================================ */

const RARITY = {
  common:    { label: 'Common',    color: '#7dd3fc', weight: 100, pts: 10 },
  uncommon:  { label: 'Uncommon',  color: '#86efac', weight: 34,  pts: 25 },
  rare:      { label: 'Rare',      color: '#c084fc', weight: 10,  pts: 60 },
  epic:      { label: 'Epic',      color: '#fb923c', weight: 3,   pts: 150 },
  legendary: { label: 'Legendary', color: '#fde047', weight: 0,   pts: 1000 },
};

/* kind — how the detector draws & how you catch it:
   helix   : charged track curling in the magnetic field
   photon  : straight line ending in an ECAL energy blob
   missing : dashed "missing energy" arrow (neutrinos!)
   jet     : collimated spray of hadron tracks (quarks & gluons)
   boss    : short-lived heavy particle — starburst vertex + decay children
   vee     : travels invisibly, then decays at a displaced vertex (V shape)
*/

const PARTICLES = {
  /* ---------------- LEPTONS ---------------- */
  electron: {
    id: 'electron', name: 'Electron', symbol: 'e⁻', type: 'Lepton',
    mass: '0.511 MeV/c²', massGeV: 0.000511, charge: -1, spin: '½',
    lifetime: 'Stable', rarity: 'common', threshold: 0.01,
    kind: 'helix', color: '#38bdf8', stopAt: 'ecal',
    discovered: '1897 — J.J. Thomson, Cavendish Laboratory (cathode rays)',
    tagline: 'The OG particle',
    funFact: 'The very first elementary particle ever discovered! Every atom in your body has electrons buzzing around its nucleus. Lightning is just trillions of electrons jumping through the sky.',
    howWeSeeIt: 'A thin curling track that stops in the electromagnetic calorimeter with a bright energy splash.',
  },
  positron: {
    id: 'positron', name: 'Positron', symbol: 'e⁺', type: 'Antimatter Lepton',
    mass: '0.511 MeV/c²', massGeV: 0.000511, charge: +1, spin: '½',
    lifetime: 'Stable (until it meets an electron!)', rarity: 'common', threshold: 0.01,
    kind: 'helix', color: '#f472b6', stopAt: 'ecal',
    discovered: '1932 — Carl Anderson, Caltech (cloud chamber)',
    tagline: 'The electron\'s evil twin',
    funFact: 'The first antimatter ever found! It is an electron\'s mirror twin with opposite charge. When a positron meets an electron, they annihilate in a flash of pure energy — hospitals use this in PET scanners.',
    howWeSeeIt: 'Curls the OPPOSITE way from an electron in the magnetic field — that\'s how Anderson knew it was antimatter.',
  },
  muon: {
    id: 'muon', name: 'Muon', symbol: 'μ⁻', type: 'Lepton',
    mass: '105.7 MeV/c²', massGeV: 0.1057, charge: -1, spin: '½',
    lifetime: '2.2 microseconds', rarity: 'common', threshold: 0.25,
    kind: 'helix', color: '#22d3ee', stopAt: 'exit',
    discovered: '1936 — Carl Anderson & Seth Neddermeyer (cosmic rays)',
    tagline: '“Who ordered that?”',
    funFact: 'A heavy electron — 207× heavier! Physicist I.I. Rabi was so surprised it existed he joked, “Who ordered that?” Muons from cosmic rays pass through your body about once a second. Say hi!',
    howWeSeeIt: 'The escape artist: it punches straight through EVERY layer of the detector and out the other side. Only muons reach the outer muon chambers.',
  },
  tau: {
    id: 'tau', name: 'Tau', symbol: 'τ⁻', type: 'Lepton',
    mass: '1,776.9 MeV/c²', massGeV: 1.7769, charge: -1, spin: '½',
    lifetime: '0.29 picoseconds', rarity: 'rare', threshold: 3.6,
    kind: 'helix', color: '#67e8f9', stopAt: 'hcal',
    discovered: '1975 — Martin Perl, SLAC (Nobel Prize 1995)',
    tagline: 'The heavyweight lepton',
    funFact: 'The electron\'s MASSIVE cousin — 3,477× heavier, heavier than an entire hydrogen atom! It lives for less than a trillionth of a second before falling apart.',
    howWeSeeIt: 'It decays almost instantly — we catch its footprints: a track that suddenly turns into a tiny spray of particles.',
  },
  neutrino: {
    id: 'neutrino', name: 'Neutrino', symbol: 'ν', type: 'Lepton',
    mass: '< 0.0000008 MeV/c² (almost nothing!)', massGeV: 0, charge: 0, spin: '½',
    lifetime: 'Stable', rarity: 'uncommon', threshold: 0.5,
    kind: 'missing', color: '#94a3b8', stopAt: 'exit',
    discovered: '1956 — Reines & Cowan, Savannah River reactor',
    tagline: 'The ghost particle',
    funFact: 'About 100 TRILLION neutrinos fly through your body every second — through walls, mountains, the whole Earth — and almost never touch anything. A light-year of solid lead would only stop half of them!',
    howWeSeeIt: 'We can\'t! We add up the energy of everything else and notice some is MISSING — that invisible missing energy is the neutrino sneaking away.',
  },

  /* ---------------- QUARKS (seen as jets!) ---------------- */
  up: {
    id: 'up', name: 'Up Quark', symbol: 'u', type: 'Quark',
    mass: '2.2 MeV/c²', massGeV: 0.0022, charge: '+⅔', spin: '½',
    lifetime: '—', rarity: 'common', threshold: 3,
    kind: 'jet', color: '#fca5a5', stopAt: 'hcal',
    discovered: '1968 — SLAC deep inelastic scattering experiments',
    tagline: 'Building block #1',
    funFact: 'Protons are made of two up quarks and one down quark. Here\'s the weird part: the quarks only weigh about 1% of the proton — the other 99% is pure energy from the force holding them together!',
    howWeSeeIt: 'Quarks can NEVER be alone (confinement!). Knock one loose and it instantly dresses up as a spray of particles flying together — a “jet”.',
  },
  down: {
    id: 'down', name: 'Down Quark', symbol: 'd', type: 'Quark',
    mass: '4.7 MeV/c²', massGeV: 0.0047, charge: '−⅓', spin: '½',
    lifetime: '—', rarity: 'common', threshold: 3,
    kind: 'jet', color: '#93c5fd', stopAt: 'hcal',
    discovered: '1968 — SLAC deep inelastic scattering experiments',
    tagline: 'Building block #2',
    funFact: 'Neutrons are one up + two down quarks. Quarks come in three “colors” (not real colors — a kind of charge), and they swap colors trillions of times a second by tossing gluons back and forth.',
    howWeSeeIt: 'A jet — a cone-shaped firework of hadrons all flying the same direction.',
  },
  strange: {
    id: 'strange', name: 'Strange Quark', symbol: 's', type: 'Quark',
    mass: '93 MeV/c²', massGeV: 0.093, charge: '−⅓', spin: '½',
    lifetime: '—', rarity: 'uncommon', threshold: 5,
    kind: 'jet', color: '#a5f3fc', stopAt: 'hcal',
    discovered: '1947–1964 — “strange” V-particles in cosmic rays; quark model by Gell-Mann',
    tagline: 'Genuinely strange',
    funFact: 'Named “strange” because particles containing it lived WAY longer than physicists expected — so strange they invented a whole new quantum number for it: strangeness!',
    howWeSeeIt: 'A jet, often containing kaons — the classic strange-quark fingerprint.',
  },
  charm: {
    id: 'charm', name: 'Charm Quark', symbol: 'c', type: 'Quark',
    mass: '1.27 GeV/c²', massGeV: 1.27, charge: '+⅔', spin: '½',
    lifetime: '—', rarity: 'rare', threshold: 8,
    kind: 'jet', color: '#fda4af', stopAt: 'hcal',
    discovered: '1974 — found inside the J/ψ at SLAC & Brookhaven simultaneously',
    tagline: 'The November Revolution',
    funFact: 'Its discovery shook physics so hard it\'s called the “November Revolution.” Two labs found it on the same day and both leaders won the Nobel Prize. It proved quarks come in pairs!',
    howWeSeeIt: 'A “c-jet” — a jet whose particles start a tiny distance away from the collision point, because charm particles fly a fraction of a millimeter before decaying.',
  },
  bottom: {
    id: 'bottom', name: 'Bottom Quark', symbol: 'b', type: 'Quark',
    mass: '4.18 GeV/c²', massGeV: 4.18, charge: '−⅓', spin: '½',
    lifetime: '—', rarity: 'rare', threshold: 20,
    kind: 'jet', color: '#d8b4fe', stopAt: 'hcal',
    discovered: '1977 — Leon Lederman\'s team, Fermilab',
    tagline: 'a.k.a. “beauty”',
    funFact: 'Some physicists call it the “beauty” quark. The LHCb experiment at CERN — a detector as big as a building — exists almost entirely to study this one quark!',
    howWeSeeIt: 'A “b-jet” with a clearly displaced starting point — b particles travel a few millimeters before decaying. Detectors tag them with silicon sensors finer than a human hair.',
  },
  top: {
    id: 'top', name: 'Top Quark', symbol: 't', type: 'Quark',
    mass: '172.7 GeV/c²', massGeV: 172.7, charge: '+⅔', spin: '½',
    lifetime: '5 × 10⁻²⁵ s (the shortest-lived particle known!)', rarity: 'epic', threshold: 350,
    kind: 'boss', color: '#fbbf24', stopAt: 'hcal',
    decay: ['bjet', 'muon+', 'neutrino'],
    decayNote: 't → W + b, then W → μ + ν',
    discovered: '1995 — CDF & DØ experiments, Fermilab Tevatron',
    tagline: 'The heavyweight champion',
    funFact: 'The heaviest elementary particle ever found — one top quark weighs as much as an entire GOLD ATOM, yet it\'s a single point with no size! It decays before it can even grab other quarks to form a hadron.',
    howWeSeeIt: 'It vanishes in a trillionth of a trillionth of a second. We reconstruct it from its children: a b-jet, a muon, and missing energy.',
  },

  /* ---------------- FORCE CARRIERS ---------------- */
  photon: {
    id: 'photon', name: 'Photon', symbol: 'γ', type: 'Gauge Boson',
    mass: '0 (massless!)', massGeV: 0, charge: 0, spin: '1',
    lifetime: 'Stable — forever', rarity: 'common', threshold: 0.01,
    kind: 'photon', color: '#fef08a', stopAt: 'ecal',
    discovered: '1905 — Einstein explains the photoelectric effect (Nobel Prize 1921)',
    tagline: 'A piece of light itself',
    funFact: 'Every bit of light — sunshine, your screen, X-rays, Wi-Fi — is made of photons. They carry the electromagnetic force and always travel at exactly the speed of light, because for a photon, time doesn\'t pass at all!',
    howWeSeeIt: 'Invisible in the tracker (no charge = no track), then BOOM — a bright energy deposit in the electromagnetic calorimeter.',
  },
  gluon: {
    id: 'gluon', name: 'Gluon', symbol: 'g', type: 'Gauge Boson',
    mass: '0 (massless)', massGeV: 0, charge: 0, spin: '1',
    lifetime: '—', rarity: 'uncommon', threshold: 10,
    kind: 'jet', color: '#6ee7b7', stopAt: 'hcal',
    discovered: '1979 — three-jet events at PETRA, DESY (Germany)',
    tagline: 'The strongest glue in the universe',
    funFact: 'Gluons carry the strong force — the super-glue holding quarks together. It\'s so strong that pulling two quarks apart creates NEW quarks out of the energy, like cutting a magnet and getting two magnets!',
    howWeSeeIt: 'Physicists found it by spotting THREE jets in a collision instead of two — the third jet was a gluon shaken loose. Find a 3-jet event!',
  },
  wboson: {
    id: 'wboson', name: 'W Boson', symbol: 'W±', type: 'Gauge Boson',
    mass: '80.4 GeV/c²', massGeV: 80.4, charge: '±1', spin: '1',
    lifetime: '3 × 10⁻²⁵ s', rarity: 'epic', threshold: 90,
    kind: 'boss', color: '#f97316', stopAt: 'hcal',
    decay: ['muon+', 'neutrino'],
    decayNote: 'W⁺ → μ⁺ + ν  (a muon plus missing energy)',
    discovered: '1983 — UA1 & UA2 experiments, CERN (Nobel Prize for Rubbia & van der Meer, 1984)',
    tagline: 'The weak force\'s muscle',
    funFact: 'The W carries the weak force — the only force that can change one kind of quark into another. Without it the Sun couldn\'t shine: the W makes the fusion reaction that powers every star!',
    howWeSeeIt: 'A single stiff muon plus a big chunk of missing energy flying the other way — the W\'s classic signature.',
  },
  zboson: {
    id: 'zboson', name: 'Z Boson', symbol: 'Z⁰', type: 'Gauge Boson',
    mass: '91.19 GeV/c²', massGeV: 91.19, charge: 0, spin: '1',
    lifetime: '3 × 10⁻²⁵ s', rarity: 'epic', threshold: 92,
    kind: 'boss', color: '#e879f9', stopAt: 'hcal',
    decay: ['muon+', 'muon-'],
    decayNote: 'Z⁰ → μ⁺ + μ⁻  (two muons, back to back)',
    discovered: '1983 — UA1 & UA2 experiments, CERN',
    tagline: 'The W\'s neutral sibling',
    funFact: 'The Z is like a heavy photon with no charge. Studying millions of Z bosons told us there are EXACTLY three families of particles in the universe — no more hiding!',
    howWeSeeIt: 'Two energetic muons shooting out back-to-back. Add up their energy and you get exactly 91 GeV — the Z\'s mass — every single time.',
  },

  /* ---------------- HADRONS: BARYONS ---------------- */
  proton: {
    id: 'proton', name: 'Proton', symbol: 'p', type: 'Baryon (uud)',
    mass: '938.3 MeV/c²', massGeV: 0.9383, charge: +1, spin: '½',
    lifetime: 'Stable (at least 10³⁴ years!)', rarity: 'common', threshold: 2,
    kind: 'helix', color: '#fb7185', stopAt: 'hcal',
    discovered: '1917 — Ernest Rutherford',
    tagline: 'The collider\'s ammunition',
    funFact: 'This is what the LHC smashes together! Protons in the LHC travel at 99.9999991% the speed of light, lapping the 27 km ring 11,245 times every second.',
    howWeSeeIt: 'A solid curved track that plows into the hadron calorimeter.',
  },
  neutron: {
    id: 'neutron', name: 'Neutron', symbol: 'n', type: 'Baryon (udd)',
    mass: '939.6 MeV/c²', massGeV: 0.9396, charge: 0, spin: '½',
    lifetime: '~15 minutes (when alone)', rarity: 'common', threshold: 2.5,
    kind: 'photon', color: '#cbd5e1', stopAt: 'hcal',
    discovered: '1932 — James Chadwick (Nobel Prize 1935)',
    tagline: 'The neutral partner',
    funFact: 'Inside an atom, neutrons live forever. But a lone neutron falls apart in about 15 minutes! Neutron stars are giant balls of them — one teaspoon would weigh a billion tons.',
    howWeSeeIt: 'No track at all (no charge!), then a surprise energy splash deep in the hadron calorimeter.',
  },
  antiproton: {
    id: 'antiproton', name: 'Antiproton', symbol: 'p̄', type: 'Antimatter Baryon',
    mass: '938.3 MeV/c²', massGeV: 0.9383, charge: -1, spin: '½',
    lifetime: 'Stable (until it touches matter!)', rarity: 'uncommon', threshold: 4,
    kind: 'helix', color: '#f0abfc', stopAt: 'hcal',
    discovered: '1955 — Segrè & Chamberlain, Berkeley Bevatron (Nobel Prize 1959)',
    tagline: 'Mirror-universe proton',
    funFact: 'CERN is the only place on Earth that bottles antimatter! Its Antimatter Factory traps antiprotons in magnetic cages — touching the wall would annihilate them instantly. 1 gram of antiprotons = energy of a small nuclear bomb (don\'t worry, making 1 gram would take 100 billion years).',
    howWeSeeIt: 'Looks like a proton but curls the opposite way, and ends with an extra-violent annihilation splash.',
  },
  lambda: {
    id: 'lambda', name: 'Lambda', symbol: 'Λ⁰', type: 'Baryon (uds)',
    mass: '1,115.7 MeV/c²', massGeV: 1.1157, charge: 0, spin: '½',
    lifetime: '0.26 nanoseconds', rarity: 'uncommon', threshold: 2.3,
    kind: 'vee', color: '#5eead4', stopAt: 'hcal',
    decay: ['proton+', 'pion-'],
    decayNote: 'Λ → p + π⁻ (the famous “V” shape)',
    discovered: '1950 — cosmic ray cloud chambers',
    tagline: 'The first strange particle',
    funFact: 'The Lambda contains a strange quark and was one of the mysterious “V particles” — it appears out of nowhere as a perfect V shape, like an invisible particle suddenly splitting in two. Because that\'s exactly what it is!',
    howWeSeeIt: 'NOTHING leaves the collision point... then suddenly, a V of two tracks appears in mid-air. The invisible neutral Lambda decayed in flight!',
  },
  sigma: {
    id: 'sigma', name: 'Sigma', symbol: 'Σ⁺', type: 'Baryon (uus)',
    mass: '1,189.4 MeV/c²', massGeV: 1.1894, charge: +1, spin: '½',
    lifetime: '0.08 nanoseconds', rarity: 'uncommon', threshold: 2.6,
    kind: 'vee', color: '#99f6e4', stopAt: 'hcal',
    decay: ['proton+', 'pizerochild'],
    decayNote: 'Σ⁺ → p + π⁰',
    discovered: '1953 — cosmic ray experiments',
    tagline: 'The kinked track',
    funFact: 'Part of the strange-particle family that baffled physicists in the 1950s. Sorting these particles into patterns is what led Murray Gell-Mann to discover quarks — like building the periodic table of particles!',
    howWeSeeIt: 'A track that suddenly KINKS — the Sigma flies a short way, then swaps into a proton heading a new direction.',
  },
  xi: {
    id: 'xi', name: 'Xi (Cascade)', symbol: 'Ξ⁻', type: 'Baryon (dss)',
    mass: '1,321.7 MeV/c²', massGeV: 1.3217, charge: -1, spin: '½',
    lifetime: '0.16 nanoseconds', rarity: 'rare', threshold: 3,
    kind: 'vee', color: '#2dd4bf', stopAt: 'hcal',
    decay: ['lambdachild', 'pion-'],
    decayNote: 'Ξ⁻ → Λ⁰ + π⁻ (a decay chain — hence “cascade”!)',
    discovered: '1952 — cosmic rays (the “cascade particle”)',
    tagline: 'The cascade',
    funFact: 'Called the “cascade” because it decays in a waterfall: the Xi becomes a Lambda, which then decays AGAIN. Two strange quarks means two strange decays — a domino chain of particles!',
    howWeSeeIt: 'A track, then a V, then the V\'s arms split again — a beautiful cascade of decays.',
  },
  omega: {
    id: 'omega', name: 'Omega', symbol: 'Ω⁻', type: 'Baryon (sss)',
    mass: '1,672.5 MeV/c²', massGeV: 1.6725, charge: -1, spin: '3/2',
    lifetime: '0.08 nanoseconds', rarity: 'epic', threshold: 3.5,
    kind: 'vee', color: '#14b8a6', stopAt: 'hcal',
    decay: ['lambdachild', 'kaon-'],
    decayNote: 'Ω⁻ → Λ⁰ + K⁻',
    discovered: '1964 — Brookhaven National Laboratory',
    tagline: 'The prediction that proved quarks',
    funFact: 'Murray Gell-Mann PREDICTED this particle — its mass, charge, everything — before anyone saw it, using his quark theory. When it showed up in 1964 exactly as predicted, physicists knew quarks were real. Three strange quarks: maximum strangeness!',
    howWeSeeIt: 'The rarest of the strange cascades — a triple-decay chain. Finding one in 1964 took scanning 100,000 photographs by hand!',
  },

  /* ---------------- HADRONS: MESONS ---------------- */
  piplus: {
    id: 'piplus', name: 'Pion', symbol: 'π⁺', type: 'Meson (ud̄)',
    mass: '139.6 MeV/c²', massGeV: 0.1396, charge: +1, spin: '0',
    lifetime: '26 nanoseconds', rarity: 'common', threshold: 0.3,
    kind: 'helix', color: '#a7f3d0', stopAt: 'hcal',
    discovered: '1947 — Cecil Powell, photographic plates on mountain tops',
    tagline: 'The most common shrapnel',
    funFact: 'Pions are the confetti of particle collisions — a single LHC smash can spray out over a hundred! They were discovered by leaving photo plates on mountain peaks to catch cosmic rays.',
    howWeSeeIt: 'Most of the curved tracks spraying from any collision are pions. The everywhere-particle.',
  },
  pizero: {
    id: 'pizero', name: 'Neutral Pion', symbol: 'π⁰', type: 'Meson',
    mass: '135.0 MeV/c²', massGeV: 0.135, charge: 0, spin: '0',
    lifetime: '0.000000085 nanoseconds', rarity: 'common', threshold: 0.3,
    kind: 'boss', color: '#fde68a', stopAt: 'ecal',
    decay: ['photonchild', 'photonchild'],
    decayNote: 'π⁰ → γ + γ',
    discovered: '1950 — Berkeley cyclotron',
    tagline: 'The light-maker',
    funFact: 'It lives for less than a billionth of a billionth of a second, then turns into two flashes of light. Almost too fast to imagine — light itself only travels the width of an atom in that time!',
    howWeSeeIt: 'Two photons bursting from the collision point in a narrow pair.',
  },
  kplus: {
    id: 'kplus', name: 'Kaon', symbol: 'K⁺', type: 'Meson (us̄)',
    mass: '493.7 MeV/c²', massGeV: 0.4937, charge: +1, spin: '0',
    lifetime: '12 nanoseconds', rarity: 'common', threshold: 1.1,
    kind: 'helix', color: '#bef264', stopAt: 'hcal',
    discovered: '1947 — Rochester & Butler, cloud chamber',
    tagline: 'Carrier of strangeness',
    funFact: 'The kaon smuggles a strange quark inside. Kaons taught us the universe is not perfectly symmetric between matter and antimatter — a clue to why anything exists at all!',
    howWeSeeIt: 'Like a pion\'s heavier cousin — a charged track, slightly stiffer for the same energy.',
  },
  kzero: {
    id: 'kzero', name: 'Neutral Kaon', symbol: 'K⁰', type: 'Meson (ds̄)',
    mass: '497.6 MeV/c²', massGeV: 0.4976, charge: 0, spin: '0',
    lifetime: 'Two personalities: 0.09 ns and 51 ns!', rarity: 'uncommon', threshold: 1.1,
    kind: 'vee', color: '#d9f99d', stopAt: 'hcal',
    decay: ['pion+', 'pion-'],
    decayNote: 'K⁰ → π⁺ + π⁻',
    discovered: '1947 — the original “V particle”',
    tagline: 'The quantum shapeshifter',
    funFact: 'The weirdest particle in physics: it constantly flips between being itself and its own antiparticle, billions of times per second. It literally can\'t decide what it is!',
    howWeSeeIt: 'An invisible traveler that suddenly becomes a V of two pions, away from the collision point.',
  },
  eta: {
    id: 'eta', name: 'Eta Meson', symbol: 'η', type: 'Meson',
    mass: '547.9 MeV/c²', massGeV: 0.5479, charge: 0, spin: '0',
    lifetime: '5 × 10⁻¹⁹ s', rarity: 'uncommon', threshold: 1.2,
    kind: 'boss', color: '#fcd34d', stopAt: 'ecal',
    decay: ['photonchild', 'photonchild'],
    decayNote: 'η → γ + γ (most often)',
    discovered: '1961 — Berkeley Bevatron',
    tagline: 'The quantum smoothie',
    funFact: 'The eta isn\'t made of one pair of quarks — it\'s a quantum BLEND of up, down, AND strange quark pairs all at once, mixed together like a smoothie. Only quantum mechanics allows that!',
    howWeSeeIt: 'A wider pair of photons than the π⁰ — more mass means a bigger opening angle.',
  },
  jpsi: {
    id: 'jpsi', name: 'J/Psi', symbol: 'J/ψ', type: 'Meson (cc̄) — “charmonium”',
    mass: '3,096.9 MeV/c²', massGeV: 3.0969, charge: 0, spin: '1',
    lifetime: '7 × 10⁻²¹ s', rarity: 'rare', threshold: 3.1,
    kind: 'boss', color: '#f9a8d4', stopAt: 'hcal',
    decay: ['muon+', 'muon-'],
    decayNote: 'J/ψ → μ⁺ + μ⁻',
    discovered: '1974 — Richter (SLAC) & Ting (Brookhaven), same week!',
    tagline: 'The two-named revolution',
    funFact: 'The only particle with two names! Two labs discovered it the same week — one called it “J”, the other “ψ” — and neither would give up, so it\'s J/ψ forever. It\'s a charm quark orbiting its own antiquark, like a tiny atom made of pure charm.',
    howWeSeeIt: 'A crisp pair of muons whose energies always add up to exactly 3.1 GeV.',
  },
  dmeson: {
    id: 'dmeson', name: 'D Meson', symbol: 'D⁰', type: 'Meson (cū)',
    mass: '1,864.8 MeV/c²', massGeV: 1.8648, charge: 0, spin: '0',
    lifetime: '0.4 picoseconds', rarity: 'rare', threshold: 3.8,
    kind: 'vee', color: '#fbcfe8', stopAt: 'hcal',
    decay: ['kaon-', 'pion+'],
    decayNote: 'D⁰ → K⁻ + π⁺',
    discovered: '1976 — SLAC',
    tagline: 'Open charm',
    funFact: 'The lightest particle with a “naked” charm quark (not hidden by its own antiquark). D mesons are also quantum shapeshifters, flipping into their antiparticles — LHCb watches them do it!',
    howWeSeeIt: 'A V-decay into a kaon and a pion, starting a hair\'s width from the collision point.',
  },
  bmeson: {
    id: 'bmeson', name: 'B Meson', symbol: 'B⁺', type: 'Meson (ub̄)',
    mass: '5,279.3 MeV/c²', massGeV: 5.2793, charge: +1, spin: '0',
    lifetime: '1.6 picoseconds', rarity: 'rare', threshold: 10.6,
    kind: 'vee', color: '#c4b5fd', stopAt: 'hcal',
    decay: ['jpsichild', 'kaon+'],
    decayNote: 'B⁺ → J/ψ + K⁺',
    discovered: '1983 — CLEO experiment, Cornell',
    tagline: 'The time-machine particle',
    funFact: 'B mesons decay slightly differently from their antimatter twins — breaking the universe\'s mirror symmetry! Studying this might explain why the Big Bang left us a universe of matter instead of nothing.',
    howWeSeeIt: 'Lives long enough to fly a few millimeters — detectors spot its displaced decay with silicon pixels thinner than paper.',
  },
  upsilon: {
    id: 'upsilon', name: 'Upsilon', symbol: 'Υ', type: 'Meson (bb̄) — “bottomonium”',
    mass: '9,460.3 MeV/c²', massGeV: 9.4603, charge: 0, spin: '1',
    lifetime: '1.2 × 10⁻²⁰ s', rarity: 'rare', threshold: 9.5,
    kind: 'boss', color: '#a78bfa', stopAt: 'hcal',
    decay: ['muon+', 'muon-'],
    decayNote: 'Υ → μ⁺ + μ⁻',
    discovered: '1977 — Lederman\'s team, Fermilab',
    tagline: 'The “Oops-Leon”',
    funFact: 'Leon Lederman\'s team announced a particle at 6 GeV that turned out to be a mistake — nicknamed the “Oops-Leon”! A year later they found the REAL Upsilon at 9.5 GeV. Even Nobel Prize winners goof sometimes.',
    howWeSeeIt: 'A muon pair adding up to 9.46 GeV — a bottom quark waltzing with its own antiquark.',
  },

  /* ---------------- THE LEGEND ---------------- */
  higgs: {
    id: 'higgs', name: 'Higgs Boson', symbol: 'H⁰', type: 'Scalar Boson',
    mass: '125.25 GeV/c²', massGeV: 125.25, charge: 0, spin: '0',
    lifetime: '1.6 × 10⁻²² s', rarity: 'legendary', threshold: 5000,
    kind: 'boss', color: '#fde047', stopAt: 'ecal',
    decay: ['photonchild', 'photonchild'],
    decayNote: 'H → γ + γ (the golden channel)',
    discovered: '4 July 2012 — ATLAS & CMS, CERN Large Hadron Collider',
    tagline: 'The “God Particle”',
    funFact: 'The Higgs field fills the entire universe like invisible syrup — particles wading through it is what gives them MASS. Peter Higgs predicted it in 1964; it took 48 years, a 27-km machine, and thousands of scientists to find it. Only 1 in 10 BILLION collisions makes one. When CERN announced it, Peter Higgs cried. So did half the audience.',
    howWeSeeIt: 'Two ultra-pure photons whose energies combine to exactly 125 GeV. One candidate proves nothing — you need enough of them to reach 5-sigma certainty: a 1-in-3.5-million chance of being a fluke!',
  },
};

/* Children used only for rendering boss/vee decays.
   'speciesId+/-' = that species with forced charge sign.
   'xxxchild' entries map to a species for discovery credit. */
const CHILD_MAP = {
  'muon+':       { species: 'muon', charge: +1 },
  'muon-':       { species: 'muon', charge: -1 },
  'pion+':       { species: 'piplus', charge: +1 },
  'pion-':       { species: 'piplus', charge: -1 },
  'kaon+':       { species: 'kplus', charge: +1 },
  'kaon-':       { species: 'kplus', charge: -1 },
  'proton+':     { species: 'proton', charge: +1 },
  'neutrino':    { species: 'neutrino', charge: 0 },
  'bjet':        { species: 'bottom', charge: 0 },
  'photonchild': { species: 'photon', charge: 0 },
  'pizerochild': { species: 'pizero', charge: 0, leaf: true },
  'lambdachild': { species: 'lambda', charge: 0, leaf: true },
  'jpsichild':   { species: 'jpsi',  charge: 0, leaf: true },
};

/* Historical machines — shown on the energy slider so kids
   ride through accelerator history as they power up. */
const MACHINE_ERAS = [
  { maxGeV: 1,     name: 'Cyclotron Era',        sub: '1930s — Lawrence\'s palm-sized spiral' },
  { maxGeV: 7,     name: 'Bevatron Era',          sub: '1954 — Berkeley, antiproton hunter' },
  { maxGeV: 65,    name: 'SPS / PETRA Era',       sub: '1976 — gluons & the CERN SPS' },
  { maxGeV: 350,   name: 'SppS Era',              sub: '1981 — CERN finds the W & Z' },
  { maxGeV: 2000,  name: 'Tevatron Era',          sub: '1983 — Fermilab, kingdom of the top quark' },
  { maxGeV: 14000, name: 'LHC Era',               sub: '2008 — CERN\'s 27 km ring, Higgs territory' },
];

const ACHIEVEMENTS = [
  { id: 'firstfire',  icon: '⚡', name: 'Power On!',            desc: 'Fire your first collision' },
  { id: 'firstdisco', icon: '🔭', name: 'Junior Physicist',     desc: 'Discover your first particle' },
  { id: 'five',       icon: '🧪', name: 'Lab Apprentice',       desc: 'Discover 5 species' },
  { id: 'antimatter', icon: '🪞', name: 'Mirror Universe',      desc: 'Discover an antimatter particle' },
  { id: 'ghost',      icon: '👻', name: 'Ghost Hunter',         desc: 'Catch a neutrino by its missing energy' },
  { id: 'strange',    icon: '🌀', name: 'Strange New World',    desc: 'Discover 3 strange particles (Λ, K, Ξ, Ω, Σ…)' },
  { id: 'november',   icon: '🍂', name: 'November Revolution',  desc: 'Discover the J/ψ' },
  { id: 'jetset',     icon: '✈️', name: 'Jet Setter',           desc: 'Discover a quark through its jet' },
  { id: 'omega',      icon: 'Ω',  name: 'Gell-Mann\'s Prophecy', desc: 'Find the Omega — the particle predicted before it was seen' },
  { id: 'fifteen',    icon: '🎓', name: 'Particle Scholar',     desc: 'Discover 15 species' },
  { id: 'forcecarrier',icon: '🏋️', name: 'Force Carrier',       desc: 'Discover both the W and Z bosons' },
  { id: 'heavyweight',icon: '🥇', name: 'Heavyweight Champion', desc: 'Discover the top quark' },
  { id: 'candidate',  icon: '✨', name: 'Something in the Data…',desc: 'Record your first Higgs candidate event' },
  { id: 'higgs',      icon: '👑', name: 'FIVE SIGMA!',          desc: 'Confirm the Higgs boson — the God Particle' },
  { id: 'all',        icon: '🏆', name: 'Standard Model Master',desc: 'Discover every particle in the Collidoscope' },
];

if (typeof module !== 'undefined') module.exports = { PARTICLES, CHILD_MAP, RARITY, MACHINE_ERAS, ACHIEVEMENTS };
